name: azure_cosmosdb
description: NoSQL connector for Azure Cosmos DB, with a SQL twist! Supports Azure Cosmos DB SQL API on Dart and Flutter platforms
version: 1.0.0
homepage: https://www.github.com/d-markey/azure_cosmosdb
repository: https://www.github.com/d-markey/azure_cosmosdb

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  retry: ^3.1.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
