name: azure_cosmosdb
description: Connector for Azure Cosmos DB on Dart and Flutter platforms. Supports Cosmos DB SQL API, indexing policies, users, permissions, and spatial types.
version: 2.0.0
homepage: https://pub.dev/packages/azure_cosmosdb
repository: https://www.github.com/d-markey/azure_cosmosdb

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  retry: ^3.1.0
  http: ^0.13.5
  murmur3: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
