name: azure_cosmosdb
description: Connector for Azure Cosmos DB on Dart and Flutter platforms. Supports Cosmos DB SQL API, indexing policies, users, permissions, and spatial types.
version: 2.2.2
homepage: https://pub.dev/packages/azure_cosmosdb
repository: https://www.github.com/d-markey/azure_cosmosdb

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  crypto: ^3.0.2
  retry: ^3.1.0
  http: ">=0.13.5 <2.0.0"
  murmur3: ^2.1.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.22.2
