name: azure_cosmosdb
description: Azure Cosmos DB SQL API for Dart and Flutter
version: 0.9.1
homepage: https://www.github.com/d-markey/azure_cosmosdb

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  retry: ^3.1.0
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
