import '../base_document.dart';
import '../cosmos_db_exceptions.dart';

@Deprecated('Use CosmosDbPermission instead.')
typedef Permission = CosmosDbPermission;

/// Permission modes
class PermissionMode {
  const PermissionMode._(this.name);

  final String name;

  static const read = PermissionMode._('Read');
  static const all = PermissionMode._('All');

  static PermissionMode parse(String name) {
    if (name == read.name) return read;
    if (name == all.name) return all;
    throw BadResponseException('Unsupported permission mode');
  }
}

/// Class representing a CosmosDB permission.
class CosmosDbPermission extends BaseDocumentWithEtag {
  CosmosDbPermission(this.id, this.mode, this.resource, [this.token]);

  @override
  final String id;

  /// The permission's mode (see [PermissionMode]).
  final PermissionMode mode;

  /// The resource covered by this permission.
  final String resource;

  /// The permission's token generated by CosmosDB.
  final String? token;

  @override
  Map<String, dynamic> toJson() => {
        'id': id,
        'permissionMode': mode.name,
        'resource': resource,
      };

  /// Builds a [CosmosDbPermission] from a CosmosDB JSON object.
  static CosmosDbPermission build(Map json) {
    final permission = CosmosDbPermission(
        json['id'],
        PermissionMode.parse(json['permissionMode']),
        json['resource'],
        json['_token']);
    permission.setEtag(json);
    return permission;
  }
}
